# -*- coding: utf-8 -*-
"""project_on online_fraud.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OtA_FvWVGV426sQak2-s3HbKvShiNyVH
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import pandas as pd
df = pd.read_excel("/content/onlinefraud.csv.xlsx")

#Basic dataset statistics
eda_summary = {
    "shape": df.shape,
    "data_types": df.dtypes,
    "missing_values": df.isnull().sum(),
    "summary_stats": df.describe(),
    "fraud_counts": df["isFraud"].value_counts(),
    "fraud_percent": df["isFraud"].value_counts(normalize=True) * 100,
    "transaction_types": df["type"].value_counts()
}

# Display each part of the summary
print("🧾 Shape of the dataset:")
print(eda_summary["shape"])
print("\n📦 Data types:")
print(eda_summary["data_types"])
print("\n🔍 Missing values:")
print(eda_summary["missing_values"])
print("\n📊 Summary statistics (numerical columns):")
print(eda_summary["summary_stats"])
print("\n🚨 Fraud counts:")
print(eda_summary["fraud_counts"])
print("\n📈 Fraud percentage:")
print(eda_summary["fraud_percent"])
print("\n💳 Transaction type distribution:")
print(eda_summary["transaction_types"])

# Detecting outliers via IQR
def detect_outliers_iqr(data, column):
    Q1 = data[column].quantile(0.25)
    Q3 = data[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    outliers = data[(data[column] < lower_bound) | (data[column] > upper_bound)]
    return outliers, lower_bound, upper_bound

# Applying to relevant numeric columns
for col in ['amount', 'oldbalanceOrg', 'newbalanceOrig', 'oldbalanceDest', 'newbalanceDest']:
    outliers, low, high = detect_outliers_iqr(df, col)
    print(f"{col}: {len(outliers)} outliers between {low} and {high}")

# Fraud analysis by type
fraud_by_type = df[df['isFraud'] == 1]['type'].value_counts()
fraud_by_type_percent = fraud_by_type / df['type'].value_counts() * 100

# Print results
print("🔍 Fraud Count by Transaction Type:")
print(fraud_by_type)

print("\n📊 Fraud Percentage by Transaction Type:")
print(fraud_by_type_percent)

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(8, 4))
sns.boxplot(x='isFraud', y='amount', data=df)
plt.yscale('log')  # Helps visualize extreme values
plt.title("Transaction Amount Distribution by Fraud Status")
plt.xlabel("isFraud (0 = Legitimate, 1 = Fraudulent)")
plt.ylabel("Transaction Amount (log scale)")
plt.grid(True)
plt.tight_layout()
plt.show()

# Calculate average balances for fraudulent transactions
fraudulent = df[df['isFraud'] == 1]
avg_fraudulent = {
    'origin_old_balance': fraudulent['oldbalanceOrg'].mean(),
    'origin_new_balance': fraudulent['newbalanceOrig'].mean(),
    'destination_old_balance': fraudulent['oldbalanceDest'].mean(),
    'destination_new_balance': fraudulent['newbalanceDest'].mean()
}

# Calculate average balances for non-fraudulent transactions
non_fraudulent = df[df['isFraud'] == 0]
avg_non_fraudulent = {
    'origin_old_balance': non_fraudulent['oldbalanceOrg'].mean(),
    'origin_new_balance': non_fraudulent['newbalanceOrig'].mean(),
    'destination_old_balance': non_fraudulent['oldbalanceDest'].mean(),
    'destination_new_balance': non_fraudulent['newbalanceDest'].mean()
}

# Combine results
average_balances = {
    'fraudulent': avg_fraudulent,
    'non_fraudulent': avg_non_fraudulent
}

print(average_balances)

# This cell was reassigning the df variable to a dictionary, causing a KeyError later.
# It has been removed to maintain the DataFrame in the df variable.
# df = {
#     'Origin Old Balance': {'Fraud': 1218656.12, 'Non-Fraud': 873629.77},
#     'Origin New Balance': {'Fraud': 33944.32, 'Non-Fraud': 894742.35},
#     'Destination Old Balance': {'Fraud': 452803.97, 'Non-Fraud': 978732.75},
#     'Destination New Balance': {'Fraud': 1077944.29, 'Non-Fraud': 1114232.79}
# }

# Create a DataFrame for plotting average balances
df_plot = pd.DataFrame(average_balances)

# Plotting the average balances
df_plot.plot(kind='bar', figsize=(6,4))
plt.title('Average Balances for Fraudulent vs. Non-Fraudulent Transactions')
plt.ylabel('Average Amount')
plt.xticks(rotation=0, ha='center')
plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

#Convert the Series to a DataFrame and reset the index
fraud_df = pd.DataFrame(fraud_by_type).reset_index()
fraud_df.columns = ['Transaction Type', 'Fraud Count']

#Plot the bar chart
ax = fraud_df.plot(kind='bar', x='Transaction Type', y='Fraud Count', figsize=(6, 4), legend=False, color='salmon')
plt.title("Fraud Count by Transaction Type")
plt.ylabel("Number of Fraudulent Transactions")
plt.xlabel("Transaction Type")
plt.xticks(rotation=45)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

#How does the frequency of fraudulent transactions change over time? Can we visualize this trend using a time series plot?
#Filter only fraud transactions
fraud_df = df[df['isFraud'] == 1]
fraud_by_step = fraud_df.groupby('step').size()

#Plotting the time series
plt.figure(figsize=(6, 4))
fraud_by_step.plot(kind='line', color='crimson', marker='o')
plt.title("Frequency of Fraudulent Transactions Over Time (Step)")
plt.xlabel("Step (Time)")
plt.ylabel("Number of Fraudulent Transactions")
plt.grid(True, linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

# Filter fraudulent and non-fraudulent transactions
fraudulent = df[df['isFraud'] == 1]
non_fraudulent = df[df['isFraud'] == 0]
# Calculate old and new balances for both types
fraudulent_balances = fraudulent[['oldbalanceOrg', 'newbalanceOrig', 'oldbalanceDest', 'newbalanceDest']]
non_fraudulent_balances = non_fraudulent[['oldbalanceOrg', 'newbalanceOrig', 'oldbalanceDest', 'newbalanceDest']]
# Calculate mean balances
mean_fraudulent = fraudulent_balances.mean()
mean_non_fraudulent = non_fraudulent_balances.mean()

# Display the results
print("Mean Balances for Fraudulent Transactions:")
print(mean_fraudulent)
print("\nMean Balances for Non-Fraudulent Transactions:")
print(mean_non_fraudulent)

# Visualize the differences
import matplotlib.pyplot as plt

labels = ['Old Balance Org', 'New Balance Orig', 'Old Balance Dest', 'New Balance Dest']
fraudulent_means = mean_fraudulent.values
non_fraudulent_means = mean_non_fraudulent.values

x = range(len(labels))
plt.bar(x, fraudulent_means, width=0.4, label='Fraudulent', color='red', align='center')
plt.bar([p + 0.4 for p in x], non_fraudulent_means, width=0.4, label='Non-Fraudulent', color='green', align='center')

plt.xlabel('Transaction Balances')
plt.ylabel('Mean Values')
plt.title('Comparison of Balances in Fraudulent vs Non-Fraudulent Transactions')
plt.xticks([p + 0.2 for p in x], labels)
plt.legend()
plt.show()

#How many unique destination accounts are involved in fraudulent transactions, and what is the average transaction amount for these accounts?
# Filter fraudulent transactions
fraudulent_transactions = df[df['isFraud'] == 1]
# Calculate unique destination accounts and average transaction amount
unique_dest_accounts = fraudulent_transactions['nameDest'].nunique()
average_transaction_amount = fraudulent_transactions['amount'].mean()
print(f"Unique destination accounts involved in fraudulent transactions: {unique_dest_accounts}")
print(f"Average transaction amount for these accounts: {average_transaction_amount}")

import matplotlib.pyplot as plt

# Data to plot
labels = ['Unique Dest Accounts', 'Avg Transaction Amount']
values = [unique_dest_accounts, average_transaction_amount]

# Create bar chart
plt.figure(figsize=(6, 4))
bars = plt.bar(labels, values, color=['royalblue', 'crimson'])
# Add value labels on top of bars
for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2.0, yval, f'{yval:,.0f}', ha='center', va='bottom')
# Customize chart
plt.title("Fraudulent Transactions Overview")
plt.ylabel("Values")
plt.grid(axis='y', linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

#What is the correlation between transaction amount and the likelihood of fraud? Can we create a scatter plot to visualize this relationship?
# Filter the data for fraud and non-fraud transactions
fraud_data = df[df['isFraud'] == 1]
non_fraud_data = df[df['isFraud'] == 0]

# Create a scatter plot
plt.figure(figsize=(6,4))
plt.scatter(non_fraud_data['amount'], non_fraud_data['isFraud'], color='blue', label='Non-Fraud', alpha=0.5)
plt.scatter(fraud_data['amount'], fraud_data['isFraud'], color='red', label='Fraud', alpha=0.5)
plt.title('Transaction Amount vs. Likelihood of Fraud')
plt.xlabel('Transaction Amount')
plt.ylabel('Likelihood of Fraud')
plt.legend()
plt.grid()
plt.show()

# Total flagged transactions
total_flagged = df[df['isFlaggedFraud'] == 1]
# Fraudulent flagged transactions
fraud_flagged = total_flagged[total_flagged['isFraud'] == 1]
# Total non-flagged transactions
total_nonflagged = df[df['isFlaggedFraud'] == 0]

# Fraudulent non-flagged transactions
fraud_nonflagged = total_nonflagged[total_nonflagged['isFraud'] == 1]

# Percentage calculations
percent_fraud_in_flagged = (len(fraud_flagged) / len(total_flagged)) * 100 if len(total_flagged) > 0 else 0
percent_fraud_in_nonflagged = (len(fraud_nonflagged) / len(total_nonflagged)) * 100
print(f"Flagged Transactions: {len(total_flagged)}")
print(f"Fraudulent Flagged Transactions: {len(fraud_flagged)} → {percent_fraud_in_flagged:.4f}%")
print(f"Non-Flagged Transactions: {len(total_nonflagged)}")
print(f"Fraudulent Non-Flagged Transactions: {len(fraud_nonflagged)} → {percent_fraud_in_nonflagged:.4f}%")

# Create a 'Category' column based on 'isFraud' and 'isFlaggedFraud'
df['Category'] = 'Non-Fraudulent & Non-Flagged'
df.loc[(df['isFraud'] == 1) & (df['isFlaggedFraud'] == 0), 'Category'] = 'Fraudulent & Non-Flagged'
df.loc[(df['isFraud'] == 0) & (df['isFlaggedFraud'] == 1), 'Category'] = 'Non-Fraudulent & Flagged'
df.loc[(df['isFraud'] == 1) & (df['isFlaggedFraud'] == 1), 'Category'] = 'Fraudulent & Flagged'

# Plotting box plot
plt.figure(figsize=(6,4))
sns.boxplot(x='Category', y='amount', data=df, palette='Set2', showfliers=False)
plt.title("Transaction Amount Distribution by Flagged Status and Fraud")
plt.ylabel("Transaction Amount")
plt.xticks(rotation=20)
plt.grid(axis='y', linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

# Group by step and calculate the mean likelihood of fraud
fraud_likelihood = df.groupby('step')['isFraud'].mean()

# Create a line graph
plt.figure(figsize=(6,4))
plt.plot(fraud_likelihood.index, fraud_likelihood.values, marker='o')
plt.title('Likelihood of Fraud by Transaction Step')
plt.xlabel('Transaction Step')
plt.ylabel('Likelihood of Fraud')
plt.grid()
plt.xticks(fraud_likelihood.index)
plt.show()